### ISSUE TITLE
Copy all Stallman photos to a single host

### ISSUE THREAD

**Issue by jdrago999** [interwho/stallman-bot#1]
**Background:**

Hard links to rando internet resources is like hard-wiring your project into the inherent entropy of the 'Net. Surely, eventually, these links will all go 404.

**Tasks:**
- Have several lengthy, intractable, pointless discussions regarding which service could possibly host these photos long-term.
- Discover that nothing exists.
- Motion that a committee be created to foster the development of said service.
- Allow time to pass, the Sun to cool, etc.
- Add said service as a primary project of GNU.
  - Do nothing. (This can go on indefinitely, so do it in parallel with all subsequent tasks.)
- Fork the project, implement highly-available file storage within the blockchain and mirror it via bittorrent.

**Alternatively:**
- Copy all the images referenced in the coffeescript and put them into this github repo.
- Update all the image source urls to point to static hosting provided by github.
- Make sure all references are https://
- ???
- PROFIT!!

**Comment by interwho** [comment]
Sorry this took so long, fixed now :100:
